server:
  port: 8081  # Historical service listening on 8081
  readTimeout: 10s
  writeTimeout: 10s
  idleTimeout: 120s

database:
  host: historical-db
  port: 5432
  user: historical_service_user
  password: historical_service_password
  dbname: historical_service
  sslmode: disable
  maxOpenConns: 25
  maxIdleConns: 5
  connMaxLifetime: 30m

userService:
  url: http://user-service:8083  # Updated to correct port
  timeout: 5s
  serviceKey: historical-service-key

strategyService:
  url: http://strategy-service:8082  # Updated to correct port
  timeout: 5s
  serviceKey: historical-service-key

kafka:
  brokers: kafka:9092
  topics:
    backtestEvents: backtest-events
    backtestCompletions: backtest-completions

storage:
  type: local
  path: /data/historical

logging:
  level: debug
  format: json