apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics-script
data:
  topics.sh: |
    #!/bin/bash
    echo "Waiting for Kafka to be ready..."
    until kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null 2>&1; do
        sleep 5
        echo "Waiting for Kafka..."
    done
    echo "Creating Kafka topics..."
    kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic strategy-events --partitions 3 --replication-factor 3
    kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic user-events --partitions 3 --replication-factor 3
    kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic user-notifications --partitions 3 --replication-factor 3
    kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic backtest-events --partitions 3 --replication-factor 3
    kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic backtest-completions --partitions 3 --replication-factor 3
    kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic marketplace-events --partitions 3 --replication-factor 3
    echo "List of topics:"
    kafka-topics.sh --bootstrap-server kafka:9092 --list
    echo "Topic creation completed!"