server:
  port: 8085
  readTimeout: 30s
  writeTimeout: 30s
  idleTimeout: 120s

storage:
  # Type can be "local" or "s3"
  type: "local"
  
  # Local storage configuration
  local:
    basePath: "/data/images"
    baseURL: "http://media-service:8085/api/v1/media"
    permissions: "0644"
  
  # S3 storage configuration
  s3:
    bucket: "app-images"
    region: "us-east-1"
    accessKey: "${AWS_ACCESS_KEY}"
    secretKey: "${AWS_SECRET_KEY}"
    baseURL: "https://app-images.s3.amazonaws.com"

auth:
  enabled: true
  serviceKey: "media-service-key"

upload:
  maxFileSize: 10485760  # 10MB
  allowedExtensions: [".jpg", ".jpeg", ".png", ".gif", ".webp"]
  maxWidth: 4096
  maxHeight: 4096
  thumbnailSizes:
    - name: "small"
      width: 150
      height: 150
    - name: "medium"
      width: 300
      height: 300
    - name: "large"
      width: 600
      height: 600

logging:
  level: "info"
  format: "json"