server:
  port: 8080
  readTimeout: 10s
  writeTimeout: 10s
  idleTimeout: 120s

database:
  host: user-db
  port: 5432
  user: user_service_user
  password: user_service_password
  dbname: user_service
  sslmode: disable
  maxOpenConns: 25
  maxIdleConns: 5
  connMaxLifetime: 30m

auth:
  jwtSecret: your_super_secret_key_for_development_only
  accessTokenDuration: 15m
  refreshTokenDuration: 7d

kafka:
  brokers: kafka:9092
  topics:
    notifications: user-notifications
    events: user-events

redis:
  url: redis:6379
  sessionPrefix: user-session:
  sessionDuration: 24h

logging:
  level: debug
  format: json