server:
  port: 8082  # Strategy service listening on 8082
  readTimeout: 10s
  writeTimeout: 10s
  idleTimeout: 120s

database:
  host: strategy-db
  port: 5432
  user: strategy_service_user
  password: strategy_service_password
  dbname: strategy_service
  sslmode: disable
  maxOpenConns: 25
  maxIdleConns: 5
  connMaxLifetime: 30m

userService:
  url: http://user-service:8083  # Updated to correct port
  timeout: 5s
  serviceKey: strategy-service-key

historicalService:
  url: http://historical-service:8081  # Updated to correct port
  timeout: 30s
  serviceKey: strategy-service-key

mediaService:
  url: http://media-service:8085  # Correct port
  timeout: 30s
  serviceKey: media-service-key

kafka:
  brokers: kafka:9092
  topics:
    strategyEvents: strategy-events
    marketplaceEvents: marketplace-events

logging:
  level: debug
  format: json