server:
  port: 8080
  readTimeout: 10s
  writeTimeout: 10s
  idleTimeout: 120s

userService:
  url: http://user-service:8083  # Updated to use correct port
  timeout: 10s

strategyService:
  url: http://strategy-service:8082  # Updated to use correct port
  timeout: 10s

historicalService:
  url: http://historical-service:8081  # Updated to use correct port
  timeout: 30s

mediaService:
  url: http://media-service:8085  # Correct port
  timeout: 30s

rateLimit:
  enabled: true
  requestsPerMinute: 60
  burstSize: 10
  clientIPHeaderName: X-Real-IP

logging:
  level: debug
  format: json