name: Trading Strategy Platform CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go mod download

      - name: Lint User Service
        run: |
          cd services/user-service
          golangci-lint run ./...

      - name: Test User Service
        run: |
          cd services/user-service
          go test -v ./...

      - name: Lint Strategy Service
        run: |
          cd services/strategy-service
          golangci-lint run ./... || echo "Skipping due to incomplete implementation"

      - name: Test Strategy Service
        run: |
          cd services/strategy-service
          go test -v ./... || echo "Skipping due to incomplete implementation"

      - name: Lint Historical Data Service
        run: |
          cd services/historical-data-service
          golangci-lint run ./... || echo "Skipping due to incomplete implementation"

      - name: Test Historical Data Service
        run: |
          cd services/historical-data-service
          go test -v ./... || echo "Skipping due to incomplete implementation"

      - name: Lint API Gateway
        run: |
          cd services/api-gateway
          golangci-lint run ./... || echo "Skipping due to incomplete implementation"

      - name: Test API Gateway
        run: |
          cd services/api-gateway
          go test -v ./... || echo "Skipping due to incomplete implementation"