name: Trading Strategy Platform Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
      
      # Set up infrastructure files
      - name: Set up infrastructure files
        run: |
          chmod +x ./setup-infrastructure.sh
          ./setup-infrastructure.sh
      
      # Build and push microservices
      - name: Build and push User Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/user-service
          push: true
          tags: ghcr.io/${{ github.repository }}/user-service:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Strategy Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/strategy-service
          push: true
          tags: ghcr.io/${{ github.repository }}/strategy-service:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Historical Data Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/historical-data-service
          push: true
          tags: ghcr.io/${{ github.repository }}/historical-data-service:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./services/api-gateway
          push: true
          tags: ghcr.io/${{ github.repository }}/api-gateway:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # Build and push infrastructure images with custom configurations
      - name: Build and push Kafka
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./infrastructure/kafka/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/kafka:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CONFIG_DIR=./infrastructure/kafka/config
      
      - name: Build and push PostgreSQL
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./infrastructure/postgres/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/postgres:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CONFIG_FILE=./infrastructure/postgres/postgres.conf
      
      - name: Build and push Redis
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./infrastructure/redis/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/redis:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CONFIG_FILE=./infrastructure/redis/redis.conf
      
      - name: Build and push TimescaleDB
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./infrastructure/timescaledb/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/timescaledb:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CONFIG_FILE=./infrastructure/timescaledb/timescaledb.conf