name: Trading Strategy Platform Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
      
      - name: Build and push User Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/user-service
          push: true
          tags: ghcr.io/${{ github.repository }}/user-service:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Strategy Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/strategy-service
          push: true
          tags: ghcr.io/${{ github.repository }}/strategy-service:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Historical Data Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/historical-data-service
          push: true
          tags: ghcr.io/${{ github.repository }}/historical-data-service:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./services/api-gateway
          push: true
          tags: ghcr.io/${{ github.repository }}/api-gateway:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}